# Generated by Django 5.1 on 2024-08-20 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Default Name", max_length=255)),
                (
                    "slug",
                    models.SlugField(
                        blank=True, default=None, max_length=255, null=True, unique=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=65)),
                (
                    "slug",
                    models.SlugField(
                        blank=True, default=None, max_length=255, null=True, unique=True
                    ),
                ),
                ("is_published", models.BooleanField(default=False)),
                ("content", models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name="tag",
            name="name",
            field=models.CharField(default="Default Name", max_length=255),
        ),
        migrations.AddField(
            model_name="tag",
            name="slug",
            field=models.SlugField(
                blank=True, default=None, max_length=255, null=True, unique=True
            ),
        ),
    ]
