# Generated by Django 5.1 on 2024-08-20 09:12

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_page_alter_post_is_published"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"verbose_name": "Post", "verbose_name_plural": "Posts"},
        ),
        migrations.AddField(
            model_name="post",
            name="category",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="blog.category",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="cover",
            field=models.ImageField(
                blank=True,
                help_text="Imagem de capa do post",
                null=True,
                upload_to="posts/%Y/%m/",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="cover_in_post_content",
            field=models.BooleanField(
                default=False, help_text="Exibir imagem de capa no conteúdo do post"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name="post",
            name="excerpt",
            field=models.CharField(default="No excerpt provided", max_length=150),
        ),
        migrations.AddField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(blank=True, default=None, to="blog.tag"),
        ),
        migrations.AddField(
            model_name="post",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="is_published",
            field=models.BooleanField(
                default=False,
                help_text="Este campo precisará estar marcado para a página ser exibida publicamente.",
            ),
        ),
    ]
